version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    container_name: flask_api
    build:
      context: ./src/API/
    ports:
      - "56041:56041"
    env_file: .env    

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "43214:43214"
    command: mongod --port 43214
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASS}
    restart: always
    env_file: .env
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MEXP_ADMIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MEXP_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 43214
