version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  api:
    container_name: flask_api
    build:
      context: ./src/API/
    ports:
      - "3000:3000"
    env_file: .env    

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    env_file: .env
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
