<template>
  <div id="app" class="archivo">
    <NavBar/>
      <router-view v-slot="{ Component }">
        <transition enter-from-class="opacity-0" enter-active-class="puff-in-center" leave-active-class="fade-out" leave-to-class="opacity-1" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
  </div>
</template>

<script>
import NavBar from './components/Navbar.vue'

export default {
  name: 'App',
  components: {
    NavBar
  },
}
  
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body{
  background: rgb(32, 32, 35);
  margin: 0;
  padding: 0;
}
button {
  font-family: "Archivo";
}

/* ----------------------------------------------
 * Generated by Animista on 2023-12-19 13:54:27 - puff-in
 * Generated by Animista on 2023-12-19 13:56:46 - fade-out
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

 /* Reduced by author for simplicty */

/**
 * ----------------------------------------
 * animation puff-in-center
 * animation fade-out
 * ----------------------------------------
 */
 @keyframes puff-in-center {
  0% {
    transform: scale(2);
    filter: blur(4px);
    opacity: 0;
  }
  100% {
    transform: scale(1);
    filter: blur(0px);
    opacity: 1;
  }
}

@keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

.puff-in-center {
	animation: puff-in-center 0.3s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
}

.fade-out {
	animation: fade-out 0.3s ease-out both;
}


@import './dist/main.css';
@import url('https://fonts.googleapis.com/css2?family=Archivo:wght@100;400&display=swap');
</style>
