<template>
  <div id="app" class="archivo">
    <NavBar/>
      <router-view v-slot="{ Component }">
        <transition enter-from-class="opacity-0" enter-active-class="puff-in-center" leave-active-class="fade-out" leave-to-class="opacity-1" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
  </div>
  <canvas id="canvas">
  </canvas>
</template>

<script>
import NavBar from './components/Navbar.vue'
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

export default {
  name: 'App',
  components: {
    NavBar
  },
}

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(75, 4/3, 0.1);
const light = new THREE.PointLight( 0xf3faf2, 1, 5);
const loader = new GLTFLoader().setPath('./');

loader.load('scene.gltf', ( gltf ) => {

  scene.add( gltf.scene );

}, undefined, function ( error ) {

console.error( error );

} );

scene.add(light);

camera.position.z = 5;
light.position.set( 50, 50, 50 );

const renderer = new THREE.WebGLRenderer();


renderer.setClearColor( 0x1ef20f, 0);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(window.devicePixelRatio);

document.body.appendChild(renderer.domElement);

</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body{
  margin: 0;
  padding: 0;
}

canvas {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  z-index: -9999;
}

button {
  font-family: "Archivo";
}

/* ----------------------------------------------
 * Generated by Animista on 2023-12-19 13:54:27 - puff-in
 * Generated by Animista on 2023-12-19 13:56:46 - fade-out
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

 /* Reduced by author for simplicty */

/**
 * ----------------------------------------
 * animation puff-in-center
 * animation fade-out
 * ----------------------------------------
 */
 @keyframes puff-in-center {
  0% {
    transform: scale(2);
    filter: blur(4px);
    opacity: 0;
  }
  100% {
    transform: scale(1);
    filter: blur(0px);
    opacity: 1;
  }
}

@keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

.puff-in-center {
	animation: puff-in-center 0.3s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
}

.fade-out {
	animation: fade-out 0.3s ease-out both;
}


@import './dist/main.css';
@import url('https://fonts.googleapis.com/css2?family=Archivo:wght@100;400&display=swap');
</style>
